# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Mod Properties
mod_version = 1.1.0
maven_group = xyz.class8
archives_base_name = class8mod

# Loom??
loom_version = 1.9.1

# Dependencies
minecraft_version = 26.1.2
loader_version = 0.19.3
fabric_api_version = 0.155.2+26.1.2

# Java??
java_version = 25